### ISSUE TITLE
Grid View issue list

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/web-stories-wp#219] opened 2021-01-06 06:14 UTC
## Bug 1

- Maximum number of columns to be set is **4**, but only **3** columns is shown if 4 option is set in the settings.

## Steps to Reproduce

- Select Grid view
- By default the number of columns selected are 2
- Increase the column from settings and observe that if number is increase to 4, it still shows 3

## Screenshots

https://user-images.githubusercontent.com/41000648/103735350-e3b7b400-5013-11eb-865c-5408ab792003.mp4

---

## Bug 2

- If odd number of stories are selected to display then the `View All Stories` option can be shown center aligned to the stories ( In my opinion )

## Screenshot

![image](https://user-images.githubusercontent.com/41000648/103735540-4d37c280-5014-11eb-94bf-6cd5406909db.png)

**Comment by divyarajmasani** [comment] 2021-01-11 07:58
> Bug 1: Maximum number of columns to be set is 4, but only 3 columns is shown if 4 option is set in the settings.

We have set minimum width for the stories, so that it doesn't look broken on smaller screens and if users have selected more columns then what the available space can accommodate the stories will wrap to next raw. This one is an expected behavior.

**Comment by pooja-muchandikar** [comment] 2021-01-12 07:11
Agreed, but for desktop it should stories in 4 columns when 4 columns are selected in the `Number of columns` settings. 

Because we are allowing user to increase the number of columns to set to 4 and in desktop also if those number of columns are not visible then its an issue right.

**Comment by divyarajmasani** [comment] 2021-01-12 07:21
> Agreed, but for desktop it should stories in 4 columns when 4 columns are selected in the `Number of columns` settings.
> 
> Because we are allowing user to increase the number of columns to set to 4 and in desktop also if those number of columns are not visible then its an issue right.

This was a design decision, with the min-width set for the stories if 4 stories can't fit in the same row it will flow down to the next row. Without the min-width it will show as per user selected columns but the stories may get squashed due to less space, which is not ideal either. 

cc: @maitreyie-chavan

**Comment by pooja-muchandikar** [comment] 2021-02-08 15:29
@maitreyie-chavan 

Can you please check the Bug 1 and the comment [here](https://github.com/rtCamp/web-stories-wp/issues/219#issuecomment-758460667)? 

Need to confirmation for same.

**Comment by maitreyie-chavan** [comment] 2021-03-01 23:44
Yup, the explanation shared is true. Closing this thread now.

**Closed by maitreyie-chavan** 2021-03-01 23:44 UTC
Labels: device:desktop, env:amp, stage:new, type:bug
